### ISSUE TITLE
Not Display - N'apparait pas

### ISSUE THREAD

**Issue by iloa08** [bruno-canada/magento2-hrefLang#4]
Bonjour,
après une installation manuelle (et vérification que le module était bien actif), je ne trouve nul part dans le code sourcé généré de hreflang.

**Comment by brnquester** [comment]
@iloa08 - Would you mind providing more details about your current setup? Magento version, template type/name, folder structure, and anything else you believe is relevant? I am sorry, I don't speak French. :)

**Comment by iloa08** [comment]
No problem, I'll try in english.
Magento 2.3.3 - Child Theme
I would like give you URL : could you send me an e-mail or give me one ?

**Comment by brnquester** [comment]
Not able to replicate the issue or troubleshoot with the information provided. Sorry.
